// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2_Vjezba.DBContext;

namespace _2_Vjezba.Migrations
{
    [DbContext(typeof(MojDBC))]
    [Migration("20201211205407_PleskBaza")]
    partial class PleskBaza
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("_2_Vjezba.EntityModels.Opcina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Opcina");
                });

            modelBuilder.Entity("_2_Vjezba.EntityModels.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BrojIndeksa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpcinaPrebivalistaID")
                        .HasColumnType("int");

                    b.Property<int>("OpcinaRodjenjaID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OpcinaPrebivalistaID");

                    b.HasIndex("OpcinaRodjenjaID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("_2_Vjezba.EntityModels.Student", b =>
                {
                    b.HasOne("_2_Vjezba.EntityModels.Opcina", "OpcinaPrebivalista")
                        .WithMany()
                        .HasForeignKey("OpcinaPrebivalistaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2_Vjezba.EntityModels.Opcina", "OpcinaRodjenja")
                        .WithMany()
                        .HasForeignKey("OpcinaRodjenjaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcinaPrebivalista");

                    b.Navigation("OpcinaRodjenja");
                });
#pragma warning restore 612, 618
        }
    }
}
